import { AGENT_INSTRUCTION_TARGET_MAP } from "@/constants/instruction-targets";
import type { AgentInstructionTarget } from "@/types/domain";
import type { GeneratorQuestion } from "./types";

/**
 * Answers returned from the custom generator form. Each entry is keyed
 * by question id; values are normalized to strings/string[]/booleans.
 */
export type GeneratorAnswers = Record<string, string | string[] | boolean>;

/**
 * Dummy generator (phase 4 spec): no AI calls. Stitches a canonical
 * instruction file for the chosen target purely from the collected
 * answers. Phase 6/7 will replace this with AI-backed rendering; the
 * surface (`generateInstructionFile`) stays the same so callers don't churn.
 */
export function generateInstructionFile(
  target: AgentInstructionTarget,
  answers: GeneratorAnswers,
  questions: readonly GeneratorQuestion[],
): { filename: string; content: string } {
  const info = AGENT_INSTRUCTION_TARGET_MAP[target];
  const filename = info?.filename ?? "AGENTS.md";
  const projectName = stringAnswer(answers, "project-name", "Untitled project");
  const summary = stringAnswer(answers, "summary", "");
  const lines: string[] = [];

  lines.push(`# ${projectName} — ${info?.label ?? target} instructions`, "");
  if (summary.trim().length > 0) {
    lines.push("> " + summary.trim(), "");
  }

  for (const q of questions) {
    const value = answers[q.id];
    if (value === undefined || value === "" || value === false) continue;
    lines.push(`## ${q.label}`, "");
    if (q.kind === "multiselect" && Array.isArray(value)) {
      lines.push(...value.map((v) => `- ${v}`), "");
    } else if (q.kind === "toggle") {
      lines.push(`Enabled: ${value ? "yes" : "no"}`, "");
    } else {
      lines.push(String(value).trim(), "");
    }
  }

  lines.push("<!-- Generated by AI Context Studio (dummy engine). -->", "");
  return { filename, content: lines.join("\n") };
}

function stringAnswer(
  answers: GeneratorAnswers,
  id: string,
  fallback = "",
): string {
  const value = answers[id];
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.join(", ");
  if (typeof value === "boolean") return value ? "true" : "false";
  return fallback;
}
