import { slugify } from "@utils";
import type { GenerationOutputKind } from "@/shared/types/provider";

import { ENGINE_BLUEPRINTS } from "./blueprints";
import { ENGINE_FIELDS } from "./fields";
import type {
  EngineAnswers,
  EngineBlueprint,
  EngineFieldId,
  EngineOutput,
} from "./types";

/**
 * System Prompt Engine core.
 *
 * The engine is a pure, deterministic function â€” no AI calls, no DOM.
 * It composes a single EngineOutput from structured answers using a
 * registry of EngineBlueprints. Every section is data-driven: an empty
 * answer yields a `null` section, collapsing it out of the output.
 *
 * Replacing this with an AI-backed implementation later requires only
 * swapping `renderBlueprint` â€” the signature and consumers are stable.
 */

export function listBlueprints(): readonly EngineBlueprint[] {
  return ENGINE_BLUEPRINTS;
}

export function getBlueprint(kind: GenerationOutputKind): EngineBlueprint {
  const bp = ENGINE_BLUEPRINTS.find((b) => b.kind === kind);
  if (!bp) {
    throw new Error(`No blueprint registered for kind "${kind}"`);
  }
  return bp;
}

export function listFields(): readonly typeof ENGINE_FIELDS[number][] {
  return ENGINE_FIELDS;
}

/**
 * Compose the artifact from answers using the given blueprint.
 *
 * Steps:
 *   1. Compute title from `titleTemplate`.
 *   2. Run each section builder; keep non-null results in order.
 *   3. Return joined Markdown + smart extension-aware filename.
 *
 * Returns null when no section produced content (i.e. answers empty for
 * the chosen blueprint) so the UI can show an explicit empty state.
 */
export function renderBlueprint(
  kind: GenerationOutputKind,
  answers: EngineAnswers,
): EngineOutput | null {
  const blueprint = getBlueprint(kind);
  const title = blueprint.titleTemplate(answers);
  const bodies: string[] = [];

  const consumed: EngineFieldId[] = [];
  for (const sectionBuilder of blueprint.sections) {
    const body = sectionBuilder.build(answers);
    if (body) bodies.push(body);
    for (const id of sectionBuilder.consumes) {
      if (!consumed.includes(id)) consumed.push(id);
    }
  }

  if (bodies.length === 0) return null;

  const heading = `# ${title}\n`;
  const content = `${heading}\n${bodies.join("\n")}\n<!-- Generated by AI Context Studio â€” System Prompt Engine -->\n`;
  const filename = `${blueprint.filenameHint}-${Date.now()}.${blueprint.extension}`;

  return {
    kind: blueprint.kind,
    title,
    filename,
    content,
    consumedFields: consumed,
  };
}

/**
 * Convenience: produce ad-hoc output without picking the blueprint from
 * the registry â€” useful for unit tests or call sites that already have a
 * blueprint reference.
 */
export function renderFromBlueprint(
  blueprint: EngineBlueprint,
  answers: EngineAnswers,
): EngineOutput | null {
  return renderBlueprint(blueprint.kind, answers);
}

/**
 * Stamp a stable filename using the rendered output title rather than the
 * blueprint hint. Called by export UI. Keeps the kind-aware extension.
 */
export function titleToFilename(title: string, blueprint: EngineBlueprint): string {
  const base = slugify(title);
  return base ? `${base}.${blueprint.extension}` : `${blueprint.filenameHint}.${blueprint.extension}`;
}

/**
 * Convenience: return the field ids the active blueprint declares as
 * consumed â€” used by the UI to high-prioritize relevant form fields.
 */
export function consumedFieldsForKind(kind: GenerationOutputKind): EngineFieldId[] {
  const blueprint = getBlueprint(kind);
  const consumed: EngineFieldId[] = [];
  for (const section of blueprint.sections) {
    for (const id of section.consumes) {
      if (!consumed.includes(id)) consumed.push(id);
    }
  }
  return consumed;
}

