import type { Workflow, WorkflowStep, WorkflowId } from "./types";

/**
 * Seed workflows for quick start
 */
export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: "feature-development-pipeline" as WorkflowId,
    name: "Feature Development Pipeline",
    description: "Complete workflow from requirements to deployed feature with code review and testing",
    version: 1,
    steps: [
      {
        id: "analyze-requirements",
        type: "skill",
        name: "Analyze Requirements",
        description: "Break down feature requirements into technical tasks",
        skillId: "analyze-requirements",
        dependsOn: [],
      },
      {
        id: "design-solution",
        type: "skill",
        name: "Design Solution",
        description: "Create technical design document",
        skillId: "design-solution",
        dependsOn: ["analyze-requirements"],
      },
      {
        id: "implement-code",
        type: "skill",
        name: "Implement Code",
        description: "Write implementation following design",
        skillId: "implement-feature",
        dependsOn: ["design-solution"],
      },
      {
        id: "write-tests",
        type: "skill",
        name: "Write Tests",
        description: "Create unit and integration tests",
        skillId: "generate-tests",
        dependsOn: ["implement-code"],
      },
      {
        id: "code-review",
        type: "skill",
        name: "Code Review",
        description: "Automated and manual code review",
        skillId: "code-review",
        dependsOn: ["write-tests"],
      },
      {
        id: "deploy",
        type: "skill",
        name: "Deploy to Staging",
        description: "Deploy and run smoke tests",
        skillId: "deploy-staging",
        dependsOn: ["code-review"],
      },
    ],
    metadata: {
      createdAt: new Date("2024-01-15").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
      version: 1,
      tags: ["development", "ci-cd", "feature"],
      isCustom: false,
    },
  },
  {
    id: "bug-fix-workflow" as WorkflowId,
    name: "Bug Fix Workflow",
    description: "Rapid bug triage, fix, verification, and deployment",
    version: 1,
    steps: [
      {
        id: "triage-bug",
        type: "skill",
        name: "Triage Bug",
        description: "Analyze bug report and reproduce",
        skillId: "triage-bug",
        dependsOn: [],
      },
      {
        id: "root-cause",
        type: "skill",
        name: "Root Cause Analysis",
        description: "Identify root cause and impact",
        skillId: "root-cause-analysis",
        dependsOn: ["triage-bug"],
      },
      {
        id: "fix-bug",
        type: "skill",
        name: "Implement Fix",
        description: "Write minimal fix with tests",
        skillId: "implement-fix",
        dependsOn: ["root-cause"],
      },
      {
        id: "verify-fix",
        type: "skill",
        name: "Verify Fix",
        description: "Run tests and verify fix works",
        skillId: "verify-fix",
        dependsOn: ["fix-bug"],
      },
      {
        id: "deploy-hotfix",
        type: "skill",
        name: "Deploy Hotfix",
        description: "Fast-track deployment to production",
        skillId: "deploy-hotfix",
        dependsOn: ["verify-fix"],
      },
    ],
    metadata: {
      createdAt: new Date("2024-02-01").toISOString(),
      updatedAt: new Date("2024-02-01").toISOString(),
      version: 1,
      tags: ["bugfix", "hotfix", "production"],
      isCustom: false,
    },
  },
  {
    id: "code-review-workflow" as WorkflowId,
    name: "Code Review Workflow",
    description: "Comprehensive code review process with security, performance, and maintainability checks",
    version: 1,
    steps: [
      {
        id: "review-changes",
        type: "skill",
        name: "Review Changes",
        description: "Analyze diff for correctness",
        skillId: "review-diff",
        dependsOn: [],
      },
      {
        id: "security-scan",
        type: "skill",
        name: "Security Scan",
        description: "Check for security vulnerabilities",
        skillId: "security-scan",
        dependsOn: ["review-changes"],
      },
      {
        id: "performance-check",
        type: "skill",
        name: "Performance Check",
        description: "Identify performance regressions",
        skillId: "performance-review",
        dependsOn: ["review-changes"],
      },
      {
        id: "maintainability-review",
        type: "skill",
        name: "Maintainability Review",
        description: "Check code quality and maintainability",
        skillId: "maintainability-review",
        dependsOn: ["review-changes"],
      },
      {
        id: "approve-request-changes",
        type: "prompt",
        name: "Approve or Request Changes",
        description: "Final decision on PR",
        promptTemplate: "Review the code changes and decide: approve or request changes.",
        dependsOn: ["security-scan", "performance-check", "maintainability-review"],
      },
    ],
    metadata: {
      createdAt: new Date("2024-01-20").toISOString(),
      updatedAt: new Date("2024-01-20").toISOString(),
      version: 1,
      tags: ["code-review", "quality", "security"],
      isCustom: false,
    },
  },
  {
    id: "refactoring-workflow" as WorkflowId,
    name: "Refactoring Workflow",
    description: "Safe refactoring with tests, incremental changes, and verification",
    version: 1,
    steps: [
      {
        id: "identify-target",
        type: "skill",
        name: "Identify Refactoring Target",
        description: "Find code that needs refactoring",
        skillId: "identify-refactor-target",
        dependsOn: [],
      },
      {
        id: "create-safety-net",
        type: "skill",
        name: "Create Safety Net",
        description: "Write characterization tests",
        skillId: "create-characterization-tests",
        dependsOn: ["identify-target"],
      },
      {
        id: "refactor-incrementally",
        type: "skill",
        name: "Refactor Incrementally",
        description: "Apply small, safe refactoring steps",
        skillId: "incremental-refactor",
        dependsOn: ["create-safety-net"],
      },
      {
        id: "verify-behavior",
        type: "skill",
        name: "Verify Behavior Preserved",
        description: "Run tests to ensure no regressions",
        skillId: "verify-refactor",
        dependsOn: ["refactor-incrementally"],
      },
      {
        id: "clean-up",
        type: "skill",
        name: "Clean Up",
        description: "Remove dead code, update docs",
        skillId: "cleanup-after-refactor",
        dependsOn: ["verify-behavior"],
      },
    ],
    metadata: {
      createdAt: new Date("2024-03-01").toISOString(),
      updatedAt: new Date("2024-03-01").toISOString(),
      version: 1,
      tags: ["refactoring", "technical-debt", "tests"],
      isCustom: false,
    },
  },
  {
    id: "documentation-workflow" as WorkflowId,
    name: "Documentation Workflow",
    description: "Generate and maintain comprehensive documentation from code",
    version: 1,
    steps: [
      {
        id: "extract-api",
        type: "skill",
        name: "Extract API Documentation",
        description: "Generate API docs from source code",
        skillId: "generate-api-docs",
        dependsOn: [],
      },
      {
        id: "write-guides",
        type: "skill",
        name: "Write User Guides",
        description: "Create tutorials and how-to guides",
        skillId: "write-user-guides",
        dependsOn: ["extract-api"],
      },
      {
        id: "create-examples",
        type: "skill",
        name: "Create Examples",
        description: "Build working code examples",
        skillId: "create-code-examples",
        dependsOn: ["extract-api"],
      },
      {
        id: "review-docs",
        type: "skill",
        name: "Review Documentation",
        description: "Check accuracy and completeness",
        skillId: "review-documentation",
        dependsOn: ["write-guides", "create-examples"],
      },
      {
        id: "publish-docs",
        type: "skill",
        name: "Publish Documentation",
        description: "Deploy to documentation site",
        skillId: "publish-docs",
        dependsOn: ["review-docs"],
      },
    ],
    metadata: {
      createdAt: new Date("2024-03-15").toISOString(),
      updatedAt: new Date("2024-03-15").toISOString(),
      version: 1,
      tags: ["documentation", "api", "guides"],
      isCustom: false,
    },
  },
];