"use client";

import type { MCPServer } from "./types";

export { MCP_CATEGORIES, MCP_CATEGORY_MAP } from "./constants/categories";

/**
 * Seed MCP server configurations.
 * These are the canonical built-in catalog entries available for installation.
 */
export const SEED_MCP_SERVERS: MCPServer[] = [
  {
    id: "filesystem",
    name: "Filesystem Server",
    description: "Access local filesystem — read, write, list directories",
    category: "filesystem",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/allowed/path"],
    envVars: [],
    capabilities: [
      { name: "read_file", kind: "tool" },
      { name: "write_file", kind: "tool" },
      { name: "list_directory", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["filesystem", "local", "official"],
  },
  {
    id: "github",
    name: "GitHub Server",
    description: "Interact with GitHub — repos, issues, PRs, actions",
    category: "git",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    envVars: [{ key: "GITHUB_PERSONAL_ACCESS_TOKEN", label: "GitHub Token", description: "Personal access token", required: true, secret: true }],
    capabilities: [
      { name: "create_issue", kind: "tool" },
      { name: "search_repos", kind: "tool" },
      { name: "get_file_contents", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["github", "git", "official"],
  },
  {
    id: "sqlite",
    name: "SQLite Server",
    description: "Query and manage SQLite databases",
    category: "database",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sqlite", "/path/to/db.sqlite"],
    envVars: [],
    capabilities: [
      { name: "query", kind: "tool" },
      { name: "list_tables", kind: "tool" },
      { name: "schema", kind: "resource" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["sqlite", "database", "official"],
  },
  {
    id: "postgres",
    name: "PostgreSQL Server",
    description: "Query PostgreSQL databases with read-only or read-write access",
    category: "database",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:pass@localhost/db"],
    envVars: [],
    capabilities: [
      { name: "query", kind: "tool" },
      { name: "schema", kind: "resource" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["postgres", "database", "official"],
  },
  {
    id: "brave-search",
    name: "Brave Search Server",
    description: "Web search via Brave Search API",
    category: "search",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-brave-search"],
    envVars: [{ key: "BRAVE_API_KEY", label: "Brave API Key", description: "Brave Search API key", required: true, secret: true }],
    capabilities: [
      { name: "brave_web_search", kind: "tool" },
      { name: "brave_local_search", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["search", "web", "official"],
  },
  {
    id: "fetch",
    name: "Fetch Server",
    description: "HTTP fetch capabilities for web content retrieval",
    category: "browser",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-fetch"],
    envVars: [],
    capabilities: [{ name: "fetch", kind: "tool" }],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["http", "web", "fetch", "official"],
  },
  {
    id: "memory",
    name: "Memory Server",
    description: "Persistent memory/key-value store for MCP clients",
    category: "memory",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-memory"],
    envVars: [],
    capabilities: [
      { name: "store", kind: "tool" },
      { name: "retrieve", kind: "tool" },
      { name: "search", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["memory", "storage", "official"],
  },
  {
    id: "time",
    name: "Time Server",
    description: "Current time and timezone utilities",
    category: "utilities",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-time"],
    envVars: [],
    capabilities: [{ name: "get_current_time", kind: "tool" }],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["time", "utility", "official"],
  },
  {
    id: "git",
    name: "Git Server",
    description: "Git repository operations — status, diff, log, commit",
    category: "git",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-git"],
    envVars: [],
    capabilities: [
      { name: "git_status", kind: "tool" },
      { name: "git_diff", kind: "tool" },
      { name: "git_log", kind: "tool" },
      { name: "git_commit", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor", "opencode"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["git", "version-control", "official"],
  },
  {
    id: "puppeteer",
    name: "Puppeteer Server",
    description: "Browser automation — screenshot, PDF, scrape, interact",
    category: "browser",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-puppeteer"],
    envVars: [],
    capabilities: [
      { name: "screenshot", kind: "tool" },
      { name: "navigate", kind: "tool" },
      { name: "click", kind: "tool" },
      { name: "evaluate", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "claude-code", "cursor"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["browser", "automation", "scraping", "official"],
  },
  {
    id: "aws-kb",
    name: "AWS Knowledge Base Server",
    description: "Query AWS documentation and best practices",
    category: "docs",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-aws-kb"],
    envVars: [],
    capabilities: [{ name: "search_aws_docs", kind: "tool" }],
    supportedClients: ["claude-desktop", "claude-code", "cursor"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["aws", "cloud", "knowledge", "official"],
  },
  {
    id: "gdrive",
    name: "Google Drive Server",
    description: "Access Google Drive files and folders",
    category: "filesystem",
    provider: "MCP Team",
    version: "1.0.0",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gdrive"],
    envVars: [
      { key: "GOOGLE_CLIENT_ID", label: "Google Client ID", required: true },
      { key: "GOOGLE_CLIENT_SECRET", label: "Google Client Secret", required: true, secret: true },
      { key: "GOOGLE_REFRESH_TOKEN", label: "Google Refresh Token", required: true, secret: true },
    ],
    capabilities: [
      { name: "list_files", kind: "tool" },
      { name: "read_file", kind: "tool" },
    ],
    supportedClients: ["claude-desktop", "cursor"],
    documentationUrl: "https://github.com/modelcontextprotocol/servers",
    tags: ["google", "drive", "cloud-storage", "official"],
  },
];
