"use client";

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Brain,
  Copy,
  Download,
  Loader2,
  Zap,
  AlertCircle,
  FileText,
  Plus,
  Trash2,
  Edit2,
  FolderOpen,
  BookOpen,
  Clipboard,
  Archive,
  Tag,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { BlueprintPreview } from "@/components/generate/blueprint-preview";
import { ApiKeyModal } from "@/components/generate/api-key-modal";

const MEMORY_TYPES = [
  { id: "context", label: "Context", icon: FileText, color: "text-blue-500" },
  { id: "knowledge", label: "Knowledge", icon: BookOpen, color: "text-green-500" },
  { id: "decision", label: "Decision", icon: Clipboard, color: "text-purple-500" },
  { id: "standard", label: "Standard", icon: Archive, color: "text-orange-500" },
  { id: "reference", label: "Reference", icon: Tag, color: "text-pink-500" },
] as const;

interface MemoryBlock {
  id: string;
  type: (typeof MEMORY_TYPES)[number]["id"];
  title: string;
  content: string;
  tags: string[];
  createdAt: string;
}

const SEED_MEMORY_BLOCKS: MemoryBlock[] = [
  {
    id: "project-overview",
    type: "context",
    title: "Project Overview",
    content: "AI Context Studio is a premium web application for AI instruction engineering. Users create, customize, manage, and export AI assets for multiple AI coding assistants.",
    tags: ["overview", "project"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "tech-stack",
    type: "knowledge",
    title: "Tech Stack",
    content: "- TypeScript 5 (strict)\n- Next.js 14 (App Router, Turbopack)\n- Tailwind CSS 3.4 + shadcn/ui\n- Zustand (state) + TanStack Query (server state)\n- Framer Motion (animations)\n- Zod (validation)\n- Prisma + PostgreSQL",
    tags: ["stack", "technologies"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "architecture-decisions",
    type: "decision",
    title: "Architecture Decisions",
    content: "- Feature-based folder structure under src/features\n- Shared UI in src/components/ui\n- State in src/lib/*-store.ts (Zustand)\n- Services in src/services (providers, storage, crypto)\n- Types in src/types (barrel exports)\n- Constants in src/constants",
    tags: ["architecture", "decisions"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "coding-standards",
    type: "standard",
    title: "Coding Standards",
    content: "- TypeScript strict mode, no `any`\n- ESLint + Prettier + TypeScript strict\n- Components: composition > inheritance\n- State: colocated, minimal, typed\n- Animations: Framer Motion presets only",
    tags: ["standards", "coding"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "api-contracts",
    type: "reference",
    title: "API Contracts",
    content: "- RESTful endpoints under /api/\n- Prisma models for data\n- Zod validation for inputs\n- Better Auth for authentication\n- Rate limiting on auth endpoints",
    tags: ["api", "contracts"],
    createdAt: new Date().toISOString(),
  },
];

export function MemoriesClient() {
  const [blocks, setBlocks] = useState<MemoryBlock[]>(SEED_MEMORY_BLOCKS);
  const [activeType, setActiveType] = useState<(typeof MEMORY_TYPES)[number]["id"]>("context");
  const [selectedBlock, setSelectedBlock] = useState<MemoryBlock | null>(blocks[0] ?? null);
  const [output, setOutput] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isAiGenerating, setIsAiGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showApiKeyModal, setShowApiKeyModal] = useState(false);
  const [aiProvider, setAiProvider] = useState<{ provider: string; apiKey: string; model?: string } | null>(null);
  const [editingBlock, setEditingBlock] = useState<MemoryBlock | null>(null);
  const [newBlockForm, setNewBlockForm] = useState<Partial<MemoryBlock>>({ type: "context", title: "", content: "", tags: [] });

  const filteredBlocks = blocks.filter((b) => b.type === activeType);

  const generateLocal = useCallback(async () => {
    if (!selectedBlock) return;
    setIsGenerating(true);
    setError(null);
    try {
      const md = `# ${selectedBlock.title}\n\n${selectedBlock.content}\n\n<!-- Generated by AI Context Studio — Memories Module -->`;
      setOutput(md);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setIsGenerating(false);
    }
  }, [selectedBlock]);

  const handleDownload = useCallback(() => {
    if (!output || !selectedBlock) return;
    const filename = `${selectedBlock.id}.md`;
    const blob = new Blob([output], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, [output, selectedBlock]);

  const handleCopy = useCallback(async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
  }, [output]);

  const handleApiKeySubmit = useCallback((provider: { provider: string; apiKey: string; model?: string }) => {
    setAiProvider(provider);
    setShowApiKeyModal(false);
  }, []);

  const handleAddBlock = useCallback(() => {
    if (!newBlockForm.title || !newBlockForm.content) return;
    const newBlock: MemoryBlock = {
      id: `custom-${Date.now()}`,
      type: newBlockForm.type || "context",
      title: newBlockForm.title,
      content: newBlockForm.content,
      tags: newBlockForm.tags || [],
      createdAt: new Date().toISOString(),
    };
    setBlocks((prev) => [...prev, newBlock]);
    setNewBlockForm({ type: "context", title: "", content: "", tags: [] });
  }, [newBlockForm]);

  const handleDeleteBlock = useCallback((id: string) => {
    setBlocks((prev) => prev.filter((b) => b.id !== id));
    if (selectedBlock?.id === id) {
      setSelectedBlock(blocks.filter((b) => b.id !== id)[0] || null);
    }
  }, [selectedBlock, blocks]);

  const MemoryTypeIcon = ({ type, className }: { type: (typeof MEMORY_TYPES)[number]["id"]; className?: string }) => {
    const memType = MEMORY_TYPES.find((t) => t.id === type);
    if (!memType) return null;
    return <memType.icon className={cn("size-3.5 shrink-0", memType.color, className)} />;
  };

  const renderSidebarItem = (block: MemoryBlock) => (
    <button
      key={block.id}
      onClick={() => setSelectedBlock(block)}
      className={cn(
        "flex w-full items-start gap-2 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors",
        selectedBlock?.id === block.id
          ? "bg-[var(--color-accent)]/10 text-[var(--color-accent)]"
          : "text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-tertiary)] hover:text-[var(--color-text-primary)]"
      )}
    >
      <MemoryTypeIcon type={block.type} />
      <div className="flex-1 min-w-0">
        <p className="truncate font-medium">{block.title}</p>
        <p className="truncate text-xs text-[var(--color-text-muted)]">{block.content.slice(0, 50)}...</p>
        <div className="mt-1.5 flex flex-wrap gap-1">
          {block.tags.slice(0, 2).map((t) => (
            <Badge key={t} variant="muted" className="text-[9px]">{t}</Badge>
          ))}
          {block.tags.length > 2 && <Badge variant="muted" className="text-[9px]">+{block.tags.length - 2}</Badge>}
        </div>
      </div>
    </button>
  );

  const renderContent = () => {
    if (!selectedBlock) {
      return (
        <div className="flex h-full items-center justify-center p-6">
          <div className="text-center">
            <Brain className="h-16 w-16 text-[var(--color-text-muted)] mx-auto mb-4" />
            <h3 className="text-lg font-medium text-[var(--color-text-secondary)]">Select a memory block</h3>
            <p className="text-sm text-[var(--color-text-muted)] mt-1">Choose from the sidebar to view and render to markdown</p>
          </div>
        </div>
      );
    }

    return (
      <div className="flex h-full flex-col overflow-hidden">
        <div className="flex h-14 items-center justify-between border-b border-[var(--color-border)] px-4">
          <div className="flex items-center gap-3">
            <MemoryTypeIcon type={selectedBlock.type} className={cn("h-6 w-6", MEMORY_TYPES.find((t) => t.id === selectedBlock.type)?.color)} />
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold text-[var(--color-text-primary)]">{selectedBlock.title}</p>
              <p className="truncate text-xs text-[var(--color-text-muted)]">{selectedBlock.type} • {selectedBlock.tags.join(", ")}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => setEditingBlock(selectedBlock)}>
              <Edit2 className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="sm" onClick={() => handleDeleteBlock(selectedBlock.id)} className="text-red-500 hover:bg-red-500/10">
              <Trash2 className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          <div className="max-w-2xl mx-auto space-y-6">
            <div className="space-y-2">
              <p className="text-sm font-medium text-[var(--color-text-secondary)]">Content</p>
              <pre className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-tertiary)] p-3 text-sm font-mono leading-relaxed text-[var(--color-text-secondary)] whitespace-pre-wrap break-words">
                {selectedBlock.content}
              </pre>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-medium text-[var(--color-text-secondary)]">Tags</p>
              <div className="flex flex-wrap gap-1">
                {selectedBlock.tags.map((t) => (
                  <Badge key={t} variant="default">{t}</Badge>
                ))}
              </div>
            </div>

            <div className="space-y-2 pt-4 border-t border-[var(--color-border)]">
              <Button
                onClick={generateLocal}
                disabled={isGenerating}
                className="w-full"
                size="lg"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating…
                  </>
                ) : (
                  <>
                    <Zap className="mr-2 h-4 w-4" />
                    Generate Markdown
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="flex-1 container-app py-16 px-4">
      <div className="mb-8 max-w-4xl">
        <h1 className="text-3xl font-bold text-[var(--color-text-primary)] mb-2">Memories Manager</h1>
        <p className="text-[var(--color-text-secondary)]">Manage memory blocks (context, knowledge, decisions, standards, references) and render to markdown.</p>
        <Separator />
      </div>

      <div className="grid gap-6 lg:grid-cols-[16rem_minmax(0,1fr)] max-w-6xl">
        {/* Sidebar */}
        <aside className="flex flex-col border-r border-[var(--color-border)] bg-[var(--color-bg-secondary)]">
          <div className="flex flex-col gap-3 p-3 border-b border-[var(--color-border)]">
            <p className="px-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--color-text-muted)]">Collections</p>
            <div className="space-y-1">
              {MEMORY_TYPES.map((type) => (
                <button
                  key={type.id}
                  onClick={() => setActiveType(type.id)}
                  className={cn(
                    "flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors",
                    activeType === type.id
                      ? "bg-[var(--color-accent)]/10 text-[var(--color-accent)]"
                      : "text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-tertiary)] hover:text-[var(--color-text-primary)]"
                  )}
                >
                  <type.icon className={cn("size-3.5 shrink-0", type.color)} />
                  <span className="truncate flex-1 capitalize">{type.label}</span>
                  <Badge variant="outline" className="text-[9px]">
                    {SEED_MEMORY_BLOCKS.filter((b) => b.type === type.id).length}
                  </Badge>
                </button>
              ))}
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-3">
            <div className="flex items-center justify-between mb-3">
              <p className="px-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--color-text-muted)]">
                Blocks ({filteredBlocks.length})
              </p>
              <Button variant="ghost" size="sm" onClick={() => setEditingBlock({ id: "", type: activeType, title: "", content: "", tags: [], createdAt: new Date().toISOString() })}>
                <Plus className="h-4 w-4 mr-1" />
                New
              </Button>
            </div>
            <div className="space-y-1">
              {filteredBlocks.map(renderSidebarItem)}
            </div>
          </div>
        </aside>

        {/* Main Content */}
        <section className="flex flex-col overflow-hidden">
          <header className="flex items-center justify-between gap-3 border-b border-[var(--color-border)] px-6 py-4">
            <div className="flex items-center gap-3">
              <span className="flex size-9 items-center justify-center rounded-lg bg-[var(--color-accent)]/10 text-[var(--color-accent)]">
                <Brain className="size-4" />
              </span>
              <div>
                <h1 className="text-sm font-semibold tracking-tight text-[var(--color-text-primary)]">Memories</h1>
                <p className="text-xs text-[var(--color-text-muted)]">Persistent context blocks for AI sessions</p>
              </div>
            </div>
          </header>

          <div className="flex-1 overflow-hidden">
            {renderContent()}
          </div>
        </section>

        {/* Mobile Preview */}
        <div className="lg:hidden mt-6">
          {output && (
            <div className="space-y-2">
              <div className="flex items-center justify-between border-b border-[var(--color-border)] p-4">
                <FileText className="h-5 w-5 text-[var(--color-text-secondary)]" />
                <div className="flex items-center gap-2">
                  <Button variant="ghost" size="sm" onClick={handleCopy}>
                    <Copy className="h-4 w-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleDownload}>
                    <Download className="h-4 w-4 mr-1" />
                    Download
                  </Button>
                </div>
              </div>
              <pre className="whitespace-pre-wrap break-words p-4 font-mono text-sm leading-relaxed text-[var(--color-text-primary)] bg-[var(--color-bg-tertiary)] rounded">
                {output}
              </pre>
            </div>
          )}
        </div>

        {/* Edit/New Block Modal */}
        {editingBlock && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50" onClick={() => setEditingBlock(null)}>
            <Card className="w-full max-w-2xl animate-slide-up" onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center justify-between p-4 border-b border-[var(--color-border)]">
                <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">
                  {editingBlock.id ? "Edit Memory Block" : "New Memory Block"}
                </h2>
                <button onClick={() => setEditingBlock(null)} className="p-1 rounded hover:bg-[var(--color-bg-secondary)] transition-colors">
                  <X className="h-5 w-5 text-[var(--color-text-muted)]" />
                </button>
              </div>
              <form onSubmit={(e) => { e.preventDefault(); handleAddBlock(); }} className="p-4 space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="block-type">Type</Label>
                  <Select value={newBlockForm.type || activeType} onValueChange={(v) => setNewBlockForm({ ...newBlockForm, type: v as any })}>
                    <SelectTrigger><SelectValue placeholder="Select type" /></SelectTrigger>
                    <SelectContent>
                      {MEMORY_TYPES.map((t) => <SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="block-title">Title</Label>
                  <Input id="block-title" value={newBlockForm.title || ""} onChange={(e) => setNewBlockForm({ ...newBlockForm, title: e.target.value })} placeholder="Block title" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="block-content">Content</Label>
                  <Textarea id="block-content" value={newBlockForm.content || ""} onChange={(e) => setNewBlockForm({ ...newBlockForm, content: e.target.value })} rows={6} placeholder="Memory content..." required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="block-tags">Tags (comma separated)</Label>
                  <Input id="block-tags" value={newBlockForm.tags?.join(", ") || ""} onChange={(e) => setNewBlockForm({ ...newBlockForm, tags: e.target.value.split(",").map(t => t.trim()).filter(Boolean) })} placeholder="tag1, tag2, tag3" />
                </div>
                <div className="flex gap-2 pt-2">
                  <Button type="button" variant="ghost" className="flex-1" onClick={() => setEditingBlock(null)}>
                    Cancel
                  </Button>
                  <Button type="submit" className="flex-1">
                    {editingBlock.id ? "Save Changes" : "Create Block"}
                  </Button>
                </div>
              </form>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
